### ISSUE TITLE
ftl-plugin to generate an ftl.toml file

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#165]
The toml file should be in `build/ftl.toml` and have contents:

```toml
module = "echo"
language = "kotlin"
```

Probably just hook into the existing code that generates `build/main`.
