### ISSUE TITLE
local otel collector is using deprecated exporter

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#3019]
```
otel-collector-1  | Error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
otel-collector-1  |
otel-collector-1  | error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
otel-collector-1  | 2024/10/07 03:13:35 collector server run finished with error: failed to get config: cannot unmarshal the configuration: decoding failed due to the following error(s):
otel-collector-1  |
otel-collector-1  | error decoding 'exporters': the logging exporter has been deprecated, use the debug exporter instead
```

debug exporter docs can be found [here](https://github.com/open-telemetry/opentelemetry-collector/blob/main/exporter/debugexporter/README.md). updating config to the following should fix the issue:
```yaml
receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
```
