### ISSUE TITLE
Consolidate on using `docker compose` in dev mode

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#3521]
We now have two paths to creating Docker containers - our own imperative functions, and one using `docker compose`. We should consolidate on one, and `docker compose` seems like the way to go.

We can also eliminate our customer "readiness" function and replace it with health checks, eg.

```
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
```
