### ISSUE TITLE
Implement per-project configuration for controlling multiple aspects of FTL at once

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#948]
I think we'll want an `ftl-project.toml` file that resides in the root of a repo, that configures the different aspects of `ftl dev`. It might look something like this:

```toml
name = "mycluster"

# Modules to auto-deploy
modules = ["./backend/modules"]

[generate.typescript]
template = "frontend/web/templates"
output = "frontend/web/src/api"

[generate.dart]
template = "frontend/flutter/templates"
output = "frontend/flutter/api"

[config]
githubUsername = "alecthomas"

[secret]
encryptionKey = "foobar"
githubApiKey = ""
```
